FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
RUN chmod +x node_modules/.bin/tsc && npm run build

FROM node:20-alpine AS production
WORKDIR /app
COPY --from=builder /app/package.json .
RUN npm install --omit=dev
COPY --from=builder /app/dist ./dist
EXPOSE 3000
CMD [ "node", "./dist/index.js" ]